sudo: false
language: java
jdk:
- oraclejdk8
before_deploy:
- rm -f target/original-*.jar
- export RELEASE_PKG_FILE=$(ls target/*.jar)
- echo "Deploying release to GitHub releases"
script: mvn clean verify
deploy:
  provider: releases
  api_key:
    secure: LMY0DXcUaXkjGkbwbn9mPXa6BTY/j+nus5PsJfFCJLPS0/LoaS+UAjsvwnubOeHrHkL9IXlB9zQ684WKdaW0tTYonSm4T4zhDLiZ5Mk0ZuVt3Cst55UAdX/VbGX+fCqPWXi3T0KUA5DgLBNewSTNTek+uYy/Sk32oFANiWZntiMY5gvCGz7s9b/e0pVrdml9QmeZWB6teZl3Pu2bNS6Zcp+zGAzdy8s9xlQTr25H5PkW822fqw6oV1DxC4YmT/MXVH4r+EOmNEAzZ8+Ws9JhdEPXs1hSbQ9fMJ/4QQ1TbSM6oNnUt7+g/OQeLVs9w0iENwI+Gk6HGkdrTnn3K7rgDo/TtvmAnt3LoBbz4RJgFnsj+l8k1XmoaeUPrAYBl9cbWnbTHMLlCxj4TPmJkRvZIxjCNTMc6d6U0nLoyAO6ewji3l4tD/9885oZ+wvipo6ziRiD/VLKSjDhTSLRsVgV47ijMlZucIFkgvilvytzPX1bJ/4l7wE4rvghJDKWUMukFftTCNTHQvLx1sPCmR5NjQ87DeMXAXLOJ0Qb5XlabNyMTZWSy58VzfaFDRdUYDK1uapThSUB7ByKqFVwhjPcRRk1yUeZseRwniJA5QKP3vgs76nUfk+L8ZDbaAP6slFpdInACM25BWQHGTaySKgHZacqM1aP5hybK4WpvYFEydk=
  file:
  - "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8
    all_branches: true